version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      #- pip install sagemaker
  pre_build:
    commands:
      #- echo Logging in to Amazon ECR...
      #- aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 963778699255.dkr.ecr.eu-west-1.amazonaws.com 
      #- aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 520713654638.dkr.ecr.eu-west-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - python create-model.py
  post_build:
    commands:
      - echo Build completed on `date`