version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install sagemaker
 
  build:
    commands:
      - echo Build started on `date`
      - python create-model.py
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - cloudformation_parameters.json
    
